import turtle

# 隐藏画笔并移动到起始点
turtle.hideturtle()
turtle.penup()
turtle.goto(-150, 0)
turtle.pendown()

# 绘制小狗的躯干
turtle.color('brown')
turtle.width(8)
turtle.forward(150)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(70)

# 绘制小狗的头部
turtle.penup()
turtle.goto(0, 70)
turtle.pendown()
turtle.color('tan')
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()

# 绘制小狗的眼睛
turtle.penup()
turtle.goto(-10, 80)
turtle.pendown()
turtle.color('white')
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()

turtle.penup()
turtle.goto(10, 80)
turtle.pendown()
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()

turtle.penup()
turtle.goto(-8, 78)
turtle.pendown()
turtle.color('black')
turtle.begin_fill()
turtle.circle(2)
turtle.end_fill()

turtle.penup()
turtle.goto(12, 78)
turtle.pendown()
turtle.begin_fill()
turtle.circle(2)
turtle.end_fill()

# 绘制小狗的耳朵
turtle.penup()
turtle.goto(0, 100)
turtle.pendown()
turtle.color('tan')
turtle.begin_fill()
turtle.right(45)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.right(135)
turtle.forward(42)
turtle.end_fill()

turtle.penup()
turtle.goto(-60, 100)
turtle.pendown()
turtle.begin_fill()
turtle.right(45)
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.right(135)
turtle.forward(42)
turtle.end_fill()

# 绘制小狗的鼻子和嘴巴
turtle.penup()
turtle.goto(-10, 60)
turtle.pendown()
turtle.color('black')
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()

turtle.penup()
turtle.goto(-20, 40)
turtle.pendown()
turtle.right(45)
turtle.width(5)
turtle.forward(30)

# 绘制小狗的腿
turtle.penup()
turtle.goto(-150, -70)
turtle.pendown()
turtle.color('brown')
turtle.begin_fill()
turtle.right(50)
turtle.forward(70)
turtle.right(120)
turtle.forward(80)
turtle.right(65)
turtle.forward(40)
turtle.right(115)
turtle.forward(75)
turtle.right(180)
turtle.forward(25)
turtle.right(75)
turtle.forward(55)
turtle.right(105)
turtle.forward(15)
turtle.end_fill()

turtle.penup()
turtle.goto(-50, -70)
turtle.pendown()
turtle.color('brown')
turtle.begin_fill()
turtle.right(50)
turtle.forward(70)
turtle.right(120)
turtle.forward(80)
turtle.right(65)
turtle.forward(40)
turtle.right(115)
turtle.forward(75)
turtle.right(180)
turtle.forward(25)
turtle.right(75)
turtle.forward(55)
turtle.right(105)
turtle.forward(15)
turtle.end_fill()

turtle.penup()
turtle.goto(20, -70)
turtle.pendown()
turtle.color('brown')
turtle.begin_fill()
turtle.right(50)
turtle.forward(70)
turtle.right(120)
turtle.forward(80)
turtle.right(65)
turtle.forward(40)
turtle.right(115)
turtle.forward(75)
turtle.right(180)
turtle.forward(25)
turtle.right(75)
turtle.forward(55)
turtle.right(105)
turtle.forward(15)
turtle.end_fill()

turtle.penup()
turtle.goto(100, -70)
turtle.pendown()
turtle.color('brown')
turtle.begin_fill()
turtle.right(50)
turtle.forward(70)
turtle.right(120)
turtle.forward(80)
turtle.right(65)
turtle.forward(40)
turtle.right(115)
turtle.forward(75)
turtle.right(180)
turtle.forward(25)
turtle.right(75)
turtle.forward(55)
turtle.right(105)
turtle.forward(15)
turtle.end_fill()

# 显示图形并保持窗口不关闭
turtle.done()
